name: Linting

on:
  push:
    branches: 
    - develop
    - main
    - 'docs/*'
  pull_request:
    branches: 
    - develop
    - main
    - 'docs/*'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  call-workflow-passing-data:
    name: Documentation
    uses: RadeonOpenCompute/rocm-docs-core/.github/workflows/linting.yml@develop
